version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:4000"  # Sử dụng biến môi trường PORT
    environment:
      - MONGO_URI=${MONGO_URI}  # Sử dụng biến môi trường MONGO_URI
      - REDIS_URL=${REDIS_URL}   # Sử dụng biến môi trường REDIS_URL
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
